### ISSUE TITLE
[Bug]: Setting heating mode on water tank also sets the climate entity to Heat

### ISSUE THREAD

**Issue by DorjeDorf** [cjaliaga/home-assistant-aquarea#114]
### The problem

I noticed that recently, when I switch my water tank to heating on my Aquarea HP - the climate entity is also switched to heating (currently it's set to idle all the time considering the summer temps outside).

What's interesting is that I have the climate entity displayed as a separate graph and entity entry on Lovelace. Their status remains idle (even though when I go into history, I can clearly see, that the climate entity is set to Heat the moment the tank is set to heating). Only once the tank is switched to off, the climate entity updates to Heating. 

I tried chaning the modes from Normal to Eco, tried manually using services to change modes - nothing changes the actual behavior. Still both the tank and climate get switched to Heating. 

I enabled debug logging, and I found this line there:

2024-06-23 17:48:53.440 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.aquarea.climate.HeatPumpClimate'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/cjaliaga/home-assistant-aquarea/issues

So here I am :) 

### What version of Home Assistant Core are you running?

This has been visible in HA 2024.5.5 and all of the recent ones. 

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you running?

v0.71

### Device description

The pump here I don't think matters a lot. It's to me a purely data exchange between the integration and HA. 

### Is the integration loading?

Yes

### Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?

Yes

### Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?

Yes

**Comment by cjaliaga** [comment]
Thanks @DorjeDorf, I'll take a look as soon as I can. The integration sends the current status + new changes to the Aquarea API and I tried to replicate their Web App behavior as much as I can so the integration is as consistent as possible. That said, the behavior that you describe doesn't look OK to me but I did that part long time ago so I might be forgetting something 😅

Trying to better understand the issue, let me know if I got it right:

1) Climate entity mode is Off
2) Tank entity is Off
3) Tank entity is switched to On (heating)
4) Climate entity mode changes to Heat

The mode and actions are different so I want to be sure I understand the issue, mode change versus action reporting.

**Comment by DorjeDorf** [comment]
Correct, although this might have been something on HA side. 
I tried to reproduce it again today (running 2024.7.1 now, when reporting it was the last 2024.06) - and it no longer happens. The error in the logs no longer appears and the Climate entity also remains off. 
For now, I'd say we can close the ticket, and reopen should this come back (hopefully not) :D
