### ISSUE TITLE
[Bug]: After latest update of home assistant the module won't start up, nonetype has no value

### ISSUE THREAD

**Issue by crasyboy42** [cjaliaga/home-assistant-aquarea#118]
### The problem

After doing the latest update today the Aquarea stopped working

### What version of Home Assistant Core are you running?

2024.8.2

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you running?

0.7.1

### Device description

1 zone
Does support cooling
has DHW

### Is the integration loading?

No

### Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?

No

### Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?

Yes

### Area of the issue

Everything is unavailable/not loading

### Anything in the logs?

```txt
2024-08-23 11:20:06.291 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('aquarea', '9e1c2729a13d08e454e2f9fd737cc671'): 133.634904967}
2024-08-23 11:20:16.089 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry [email] for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 47, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by RobertJurs** [comment]
This started happening to me as well today, after I updated HACS to version 2.0.0.

Note:
Right after my update and for the last 30 mins i I cannot connect to the https://aquarea-smart.panasonic.com/ using web portal or app.
Looks like it is down.

**Comment by crasyboy42** [comment]
I see its down now for me as well, when i originally updated it was working still.

**Comment by flix4f** [comment]
I am on 2024.6.4 and HACS 1.34.0 and see the same issue.

**Comment by RobertJurs** [comment]
https://aquarea-smart.panasonic.com/ is now up again. And my integration is able to connect and works OK.

Now on:
HACS version 2.0.0

Looks like my issue was only related to panasonic being down.
It must just have been a very unfortunate that it happened right when I updated HACS, sorry for the confusion.

My Aquarea version stil say 0.7.0 though.

**Comment by GermanCaruncho** [comment]
Same mistake. It started for me at 10:43. I updated HACS days ago. The last one I did was last night and it was the HAOS CORE

**Comment by crasyboy42** [comment]
Mine seems to be working again, guess the web portal must have been cached for me or something.
@RobertJurs you might need to force the redownload in HACS itself, I needed to do that as well.
