### ISSUE TITLE
[Question]: [Panasonic ID] Notification of Panasonic ID login

### ISSUE THREAD

**Issue by sprzednowek** [cjaliaga/home-assistant-aquarea#122]
### The problem

I started receiving emails as below
do any of you receive such as well? can that be because of the hass integration?

======

[Panasonic ID] Notification of Panasonic ID login

Thank you very much for using a Panasonic ID.
You have logged in to your Panasonic ID.

This email is sent to you when you have logged in to your Panasonic ID so that you can use Panasonic services safely.
If you do not know why you have received this email and have not logged in to your Panasonic ID, a third party may have performed an unauthorized login. Please change your password as soon as possible.

------------------------------------------------------------------------
    Panasonic ID customer support
        https://accountglb.digital.panasonic.com/
------------------------------------------------------------------------

### What version of Home Assistant Core are you running?

latest

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you running?

latest

### Device description

not relevant

### Is the integration loading?

Yes

### Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?

Yes

### Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?

Yes

**Comment by Pihlflykt** [comment]
Plus one on that one! Had to set up an email rule to move all emails to a separate folder. Several emails per minute. :D

**Comment by SP2FET** [comment]
it's related to this one:
https://github.com/cjaliaga/home-assistant-aquarea/issues/121

I also got this mail spam :)

**Comment by sprzednowek** [comment]
thx, yes just saw the other ticket created and I can confirm that for me the hass integration stopped working as well
so we can close the ticket I created as duplicate

BR,
Sławek

**Comment by enzzo-ux** [comment]
same problem, probably 2 step verification

**Comment by valordk** [comment]
Same problem here, since this morning. Restarting the HA shows the Aquarea Smart Cloud authentication has expired.  Going in and reentering the password shows an error "Unexpected Error"
![image](https://github.com/user-attachments/assets/90cf6285-9273-4c01-8fb5-65d69f2b790c)

**Comment by hope55** [comment]
Same problem here! I had to disable all Aquarea entries in Settings/Integrations/Auquarea Smart Cloud to stop the email flood into my mailbox.

**Comment by Marcin685** [comment]
is this the end of the application?

**Comment by agnarvold** [comment]
Same here - flood of emails and broken integration:(

**Comment by Szakiati** [comment]
Same issue :(

**Comment by valordk** [comment]
Log show:
`Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 334, in __login_production
    csrf = response.cookies.get("_csrf").value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'`

**Comment by mirddin** [comment]
Same problem, MFA enforcement

**Comment by malvin84** [comment]
+1

**Comment by malvin84** [comment]
> is this the end of the application?

Hope not. This has been one of the most useful integrations I have.

**Comment by blackvara** [comment]
same problem

**Comment by Andkago** [comment]
I have the same issue +1

**Comment by jpietryszak** [comment]
It started to works again seams like they reverted changes they made

**Comment by jpvis** [comment]
Works again

**Comment by sprzednowek** [comment]
yep, I confirm it's working now. Let's see for how long they have reverted the changes :)

**Comment by sprzednowek** [comment]
resolving as issue is gone for now
