### ISSUE TITLE
Cant change setpoint

### ISSUE THREAD

**Issue by eliashe92** [cjaliaga/home-assistant-aquarea#13]
Thanks for the great work you have done. I have been waiting a long while for the ability to integrate my air to water heat pump (WH-MXC12H9E8).
Current temperature, tank temperature, outside temperature and status seems to be working fine

I get the following message when i try to change set point (added the climate object to thermostat card)
"Failed to call service climate/set_temperature. API error: 1000-0999 - Logged out due to system error. Please login after a while"

The set point of my heat pump is normally adjusted +- 5 degrees from a base setpoint that changes depending on the outdoor temperature.
I have tried to reload the integration, is there something else I can try?

**Comment by cjaliaga** [comment]
Thanks @eliashe92. 

I think the work on #9 should help here, I think it could be just that, I'll work on it later today and let you know 😊

Could you also show me the screen on the Panasonic Aquarea page when you click on the temperature for the zone (where allows you to set the temperature? Just to confirm something.

**Comment by eliashe92** [comment]
Great :)

Here are picture from heat (floor heating)
![image](https://user-images.githubusercontent.com/71583032/189375723-13673922-e8a5-4c7a-9d0f-34d6eaa41b56.png)

-5
![image](https://user-images.githubusercontent.com/71583032/189376272-ca6ba500-cb1f-4fe0-8863-353ba6973712.png)

+5
![image](https://user-images.githubusercontent.com/71583032/189376351-8c1f1677-b49c-41e5-901c-e0443ebb2c03.png)


Tank heating
![image](https://user-images.githubusercontent.com/71583032/189376015-3f3c185e-0d7d-4f7a-a3f6-4bb7e95825e2.png)

min 40 deg
![image](https://user-images.githubusercontent.com/71583032/189376510-4b843e21-7016-45c5-a746-4efd5a648ad9.png)

max 
![image](https://user-images.githubusercontent.com/71583032/189376605-b430b13c-62f9-4540-b611-b9f46ac461e9.png)

**Comment by cjaliaga** [comment]
@eliashe92 I've released v0.1.4 https://github.com/cjaliaga/home-assistant-aquarea/releases/tag/v0.1.4 with the fix. Please let me know if now you're able to modify the set temperature or if there's anything missing.

**Comment by eliashe92** [comment]
It seems to be going in the right direction, I now get the possibility to change setpoint, but get the following fault message when for the heat pump, se picture (adjusting setpoint for the tank seems to be working fine👍)

Heat pump
![Screenshot_20220910-102746_Home Assistant](https://user-images.githubusercontent.com/71583032/189475956-5a373952-5ad8-4153-b32f-c7f54a4e8911.jpg)

Tank
![Screenshot_20220910-104034_Home Assistant](https://user-images.githubusercontent.com/71583032/189475974-877cf1a5-1917-43c0-a020-b48b4c6d8297.jpg)

![Screenshot_20220910-104446_Home Assistant](https://user-images.githubusercontent.com/71583032/189475992-9e4d46aa-1850-48df-8fe5-153a7471d29c.jpg)

**Comment by cjaliaga** [comment]
@eliashe92 can you please try with v0.1.5? Hopefully this is the one 🤞

**Comment by eliashe92** [comment]
👏👏👏 Works perfectly now, thanks a lot!!
Have you lookes into the possibilities to use Aquarea service account? From there it is possible to see a lot of information (power usage, power consumtion, pump flow and so on)

**Comment by cjaliaga** [comment]
Yaay!! 

I've looked at the service account and I have to say that API is a pain in the ***  to say something 😂

That said, the main goal of the integration is to work as much as possible with aquarea smart as it's what most people uses, the service one is for installers, even if we can register ourselves as installers (as we both have done 😁). 

We can study the possibilities in the future, either with a complementary integration or trying to extend this one in a way that makes sense. 

Coming back to the power consumption and usage, lucky enough, they can be obtained using the normal API, and that's something I'll work on soon. Pump flow or the possibility of fully restarting the device when there's an error are things that from my investigations, I only found possible using the service account.

**Comment by eliashe92** [comment]
It would be much appreciated to get the power consumption and usage (I was not aware it was possible to get from the standard user)
Should the tank setpoint also be integer? (From the Aquarea app and control panel it is only possible to change in 1 degree steps)

Again, thanks for your great work!😀

**Comment by cjaliaga** [comment]
My pleasure, thanks a lot for all the testing, it makes all the difference, instead of me trying to guess how all different devices will behave 😄

> Should the tank setpoint also be integer? (From the Aquarea app and control panel it is only possible to change in 1 degree steps)

Yes, the tank setpoint is currently converting the value to integer before sending it to the API, the problem is with the water heater entity that doesn't support setting the step (https://developers.home-assistant.io/docs/core/entity/water-heater/) and the UI moves on a half degree per step basis. The climate entity on the other hand exposes the _target_temperature_step_ property that can be set to configure a 1 degree step: https://developers.home-assistant.io/docs/core/entity/climate
