### ISSUE TITLE
Unable to set 0 setpoint in hvac

### ISSUE THREAD

**Issue by Toma82** [cjaliaga/home-assistant-aquarea#24]
Hi, I don't know if it's just for me but I can't set 0. Other values ​​-5, -4, -3, -2, - 1,1,2,3,4 5 changes without problem, but 0 doesn't

**Comment by egrigat** [comment]
Same here, 0 is not accepted by the integration. Same problem with water tank. It's not possible for me to set 40°C for the tank.

**Comment by cjaliaga** [comment]
Thanks folks. I think I found the reason of both issues, I'll work on getting them fixed.

@egrigat one question regarding your water tank, could you show me the attributes of the water_heater entity to see if that confirm my suspicions? You can see them in Developer Tools -> States:

![image](https://user-images.githubusercontent.com/1939768/192297774-ae0d9cc4-8402-4cb1-b1d7-1fb556eab752.png)

**Comment by Toma82** [comment]
hi 
![image](https://user-images.githubusercontent.com/81713401/192347262-51ab498d-c6cf-45f4-a4cc-840ec7842b25.png)

**Comment by egrigat** [comment]
![image](https://user-images.githubusercontent.com/113016835/192350570-ddfa62b5-233a-47b3-a92e-be7fba79fc5f.png)

**Comment by cjaliaga** [comment]
Thanks both! I'll update [aioaquarea](https://github.com/cjaliaga/aioaquarea) with the fix for the "40º" issue, fix the 0º issue in the integration itself and release a version with both fixes.

**Comment by Toma82** [comment]
[cjaliaga](https://github.com/cjaliaga) great Thanks and a good job keep it up :)

**Comment by cjaliaga** [comment]
I just published the new release. Please let me know if you find any further issue or if everything works as it should be 😃

**Comment by egrigat** [comment]
Hi @cjaliaga , it's possible now to set 0°C for heating and 40°C for the tank. Thank you for your work and the update!
