### ISSUE TITLE
'DeviceZone' object has no attribute 'status'

### ISSUE THREAD

**Issue by AlessandroAloisi** [cjaliaga/home-assistant-aquarea#29]
Hi,

I have an Aquarea Heat Pump with 2 Zones and a 200l Tank. The integration is the version 0.2.1.

When i try to change the mode of a Zone the integration reply with "Invocazione del servizio climate/set_hvac_mode non riuscita. 'DeviceZone' object has no attribute 'status'".

**Comment by cjaliaga** [comment]
Hello @AlessandroAloisi, could you please provide the integration logs so I can investigate it?

Thanks,
Carlos

**Comment by AlessandroAloisi** [comment]
Hi Carlos,




where i can find the logs ?




Alessandro Aloisi

**Comment by cjaliaga** [comment]
You can use this redirect link: https://my.home-assistant.io/redirect/logs/ 

There you can look for "aquarea" and click on "Load Full Logs". They should appear there 😃 It will contain your device id and email, please feel free to delete those details:

`2022-09-27 20:18:33.638 ERROR (MainThread) [custom_components.aquarea.coordinator] Unexpected error fetching aquarea-email@email.com-DEVICEID data: API error`

**Comment by AlessandroAloisi** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/aquarea/climate.py:181
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:08:38 (2 occurrences)
Last logged: 20:08:40

[547405690624] 'DeviceZone' object has no attribute 'status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/aquarea/climate.py", line 181, in async_set_hvac_mode
    await self.coordinator.device.set_mode(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 567, in set_mode
    zones[zone.zone_id] = zone.status
AttributeError: 'DeviceZone' object has no attribute 'status'




Inviato da Posta per Windows

Da: Carlos J. Aliaga
Inviato: martedì 4 ottobre 2022 15:33
A: cjaliaga/home-assistant-aquarea
Cc: AlessandroAloisi; Mention
Oggetto: Re: [cjaliaga/home-assistant-aquarea] 'DeviceZone' object has noattribute 'status' (Issue #29)

You can use this redirect link: https://my.home-assistant.io/redirect/logs/
There you can look for "aquarea" and click on "Load Full Logs". They should appear there 😃 It will contain your device id and email, please feel free to delete those details:
2022-09-27 20:18:33.638 ERROR (MainThread) [custom_components.aquarea.coordinator] Unexpected error fetching ***@***.*** data: API error

**Comment by AlessandroAloisi** [comment]
2022-10-04 20:08:40.443 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [MyDeviceID] 'DeviceZone' object has no attribute 'status'

Inviato da Posta per Windows

Da: Carlos J. Aliaga
Inviato: martedì 4 ottobre 2022 15:33
A: cjaliaga/home-assistant-aquarea
Cc: AlessandroAloisi; Mention
Oggetto: Re: [cjaliaga/home-assistant-aquarea] 'DeviceZone' object has noattribute 'status' (Issue #29)

You can use this redirect link: https://my.home-assistant.io/redirect/logs/
There you can look for "aquarea" and click on "Load Full Logs". They should appear there 😃 It will contain your device id and email, please feel free to delete those details:
2022-09-27 20:18:33.638 ERROR (MainThread) [custom_components.aquarea.coordinator] Unexpected error fetching ***@***.*** data: API error

**Comment by cjaliaga** [comment]
Hey @AlessandroAloisi, I need to see the responses of the Aquarea API for your device in order to understand what's happening here. 

For that I need that you:

1) Disable the integration in Home Asssistant
2) Open the Aquarea page in your browser: https://aquarea-smart.panasonic.com/ 
3) Open the developer tools for your browser: [Guidance](https://www.computerhope.com/issues/ch002153.htm)
4) Open the network tab
5) Log in
6) Wait a bit, probably more than 30 seconds to let the page refresh data
7) In the network tab you will see a request like this: 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/1939768/194417837-16a84cc2-86d2-407b-8788-d4b6b9f72b8b.png">

8) Double-click on it so it opens in a new tab
9) Copy the JSON that will appear there and send it to me
10) In a new tab also open: https://aquarea-smart.panasonic.com/remote/v1/api/devices 
11) Copy this JSON and also send it to me

Please let me know if you have any doubt.

Thanks,
Carlos

**Comment by AlessandroAloisi** [comment]
Your Point 9 JSON:

{"accessToken":{"token":"d2b49fdb-218f-44ec-b212-2d55b9c6e506"},"errorCode":0,"status":[{"deiceStatus":0,"operationStatus":1,"specialStatus":[{"specialMode":1,"operationStatus":0},{"specialMode":2,"operationStatus":0}],"zoneStatus":[{"operationStatus":0,"ecoHeat":-2,"coolMin":18,"heatMin":10,"comfortCool":-2,"temparatureNow":24,"coolSet":26,"zoneId":1,"comfortHeat":2,"heatMax":30,"coolMax":35,"ecoCool":2,"heatSet":20},{"operationStatus":0,"ecoHeat":-2,"coolMin":18,"heatMin":10,"comfortCool":-2,"temparatureNow":24,"coolSet":26,"zoneId":2,"comfortHeat":2,"heatMax":30,"coolMax":35,"ecoCool":2,"heatSet":20}],"outdoorNow":17,"operationMode":0,"holidayTimer":0,"deviceGuid":"008007B755105476001434545313831373030634345373130434345373138313931304300000000","bivalent":0,"tankStatus":[{"operationStatus":1,"temparatureNow":51,"heatMax":65,"heatMin":40,"heatSet":48}],"informationMessage":0,"pumpDuty":0,"quietMode":0,"pendingUser":0,"direction":1}]}

Your Point 11:

{"accessToken":{"token":"d2b49fdb-218f-44ec-b212-2d55b9c6e506"},"device":[{"deviceGuid":"B755105476","configration":[{"zoneInfo":[{"zoneSensor":"Thermistor","coolMode":"enable","heatSensor":"Compensation curve","coolSensor":"Direct","outdoorType":"STD","zoneId":1,"zoneType":"Room","zoneName":"P.Terra"},{"zoneSensor":"Thermistor","coolMode":"enable","heatSensor":"Compensation curve","coolSensor":"Direct","outdoorType":"STD","zoneId":2,"zoneType":"Room","zoneName":"P.Primo"}],"a2wName":"Aquarea","operationMode":"Heat","deviceGuid":"007B755105476","lastErrorNumber":"","bivalent":"No","specialStatus":0,"tankInfo":[{"tankType":"Internal","tank":"Yes"}],"firmVersion":"040102"}]}],"errorCode":0}

**Comment by cjaliaga** [comment]
@AlessandroAloisi Thanks a lot for all the help debugging the issue. I just published a new version that should fix the issue. Please let me know if it works for you and please re-open the issue in case it doesn't.
