### ISSUE TITLE
Error after setup of the integration

### ISSUE THREAD

**Issue by pjbaert** [cjaliaga/home-assistant-aquarea#32]
After downloading the integration via HACS, I tried to install the integration.
I get the prompt that asks me for my AQUAREA Smart Cloud user info.
After submitting, I return to the integration overview and get the succes message.

On the integration overview page, I do however notice the failed setup error on the Aquara tile with a 'check the logs' link.

The log contains this:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/aquarea/__init__.py:64
Integration: Aquarea Smart Cloud (documentation, issues)
First occurred: 18:18:20 (1 occurrences)
Last logged: 18:18:20

Error setting up entry <username@gmail.com> for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aquarea/__init__.py", line 64, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
```

**Comment by cjaliaga** [comment]
Hello @pjbaert,

What version of Home Assistant are you running on your system? The minimum supported version of Home Assistant is 2022.8 due to this: [Waiting for config entry platforms | Home Assistant Developer Docs](https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/)

I'll get the README updated with this information.

**Comment by pjbaert** [comment]
Thank you for your respons @cjaliaga !
Upgrading my Home Assistant to the lastest stable version was indeed the solution.

Thank you for including this in the Readme :)
Looking forward to test it out!

**Comment by cjaliaga** [comment]
Awesome, happy to see it's working now 😃
