### ISSUE TITLE
Only 3 entities?

### ISSUE THREAD

**Issue by sorenfisker** [cjaliaga/home-assistant-aquarea#46]
Using this integration with WH-MDC05J3E5 I get only 3 entities.

Do I need to configure something to get access to all the settings in Comfort Cloud?

![image](https://user-images.githubusercontent.com/60732616/229528018-2c0a89cb-6821-46c1-9b60-10c807e75870.png)

**Comment by cjaliaga** [comment]
@sorenfisker in the readme you can see the features the integration currently supports: https://github.com/cjaliaga/home-assistant-aquarea#features 

This is an OSS project and I'm more than happy to accept contributions (docs, translations, new features) and super grateful with the people that already used part of their free time to contribute to the project.

Here you can find the library that connects to the Confort Cloud API: https://github.com/cjaliaga/aioaquarea in case new features need to be added there to support the new entities in the integration.
