### ISSUE TITLE
Integration stopped working - session is closed error in logs

### ISSUE THREAD

**Issue by DorjeDorf** [cjaliaga/home-assistant-aquarea#47]
Hi,

I've noticed the integration stopped working for me a couple days ago. 
Looking into the logs, this is what I am seeing for the integration. 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 52, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/aioaquarea/core.py", line 201, in login
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioaquarea/core.py", line 154, in request
    resp = await self._sess.request(method, AQUAREA_SERVICE_BASE + url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed`

Logger: homeassistant.config_entries
Source: custom_components/aquarea/__init__.py:52
Integration: Aquarea Smart Cloud ([documentation](https://github.com/cjaliaga/home-assistant-aquarea), [issues](https://github.com/cjaliaga/home-assistant-aquarea/issues))
First occurred: July 14, 2023 at 3:14:58 PM (7 occurrences)
Last logged: 11:17:58 AM

The versions I'm running are all up to date. 
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3

I have accepted the new terms pushed by Panasonic onto users via the app and the web site, I checking in with the account I am using for the integration - they all can use the phone app and the web view. 

Has anyone else seen this? 

Thanks.

**Comment by nbai777** [comment]
I have the same issue, form me since july 24th...

**Comment by DorjeDorf** [comment]
Update from me. I turned the integration off for a couple days. 
After the recent update of HA - I turned it back on and saw it to be working again. Not sure what changed, but works so far.

**Comment by haydnw** [comment]
I've just installed a CZ-TAW1 and the integration for the first time, and am getting the same error.

**Comment by haydnw** [comment]
No worries, thanks. I tried actively signing out of both devices I'd used with the account. Still didn't work. I also tried creating a second user account and giving it access to the Aquarea device (granting permission from the first account!) but that also didn't work. I couldn't see anything on the Smart Cloud website which was "_Sign out user from all devices_" or similar. So I've run out of ideas!

**Comment by nbai777** [comment]
Hello,

Unfortunately its still not working for me. Installed newest HA, restarted multiple times, also tried changing my Panasonic password...

**Comment by nbai777** [comment]
For your info the integration started working for me again on sept 13th (withouth any update etc), it was working fine until sept 21st, since then it returns the same error...

**Comment by haydnw** [comment]
Thanks - my wifi connection was dodgy so it has taken me until today to get a network cable out to the heatpump. I removed the failed device from the integration and tried once more, and it worked perfectly first time. I have no idea if it is anything to do with the better connection (unlikely?) but seems OK now. Although I have only had it running in HA for about ten minutes!

**Comment by yuliyantsvetkov** [comment]
Same here:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 52, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/aioaquarea/core.py", line 201, in login
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioaquarea/core.py", line 154, in request
    resp = await self._sess.request(method, AQUAREA_SERVICE_BASE + url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed`

**Comment by jaypikay** [comment]
> For your info the integration started working for me again on sept 13th (withouth any update etc), it was working fine until sept 21st, since then it returns the same error...

It also stopped working for me recently with the same error. Unfortunately I haven't figured out why.

**Comment by cjaliaga** [comment]
I just published 0.4.1 with some changes on entry load. Could you please give it a try to see if it makes any difference on those messages?

**Comment by cjaliaga** [comment]
I'm going to close this one as completed since the fix on 0.4.1 seems to be removed the "session is closed" issue. That said, the real reason (such connectivity issues to/from adapter to Panasonic Cloud) can now surface.

I'll keep the other issue opened https://github.com/cjaliaga/home-assistant-aquarea/issues/49 for more follow-ups if needed it.
