### ISSUE TITLE
Weekly schedule not visible in entities

### ISSUE THREAD

**Issue by vaibhavratnaparkhi** [cjaliaga/home-assistant-aquarea#55]
Weekly schedule not available 
![Screenshot_2023-11-05-19-10-09-44_c3a231c25ed346e59462e84656a70e50](https://github.com/cjaliaga/home-assistant-aquarea/assets/149868727/0f90f455-2192-46be-96da-0645959566de)

**Comment by cjaliaga** [comment]
Duplicated of #2
