### ISSUE TITLE
Integration crashed after update

### ISSUE THREAD

**Issue by formiification** [cjaliaga/home-assistant-aquarea#59]
`Logger: homeassistant.config_entries
Source: config_entries.py:642
First occurred: 13:41:26 (1 occurrences)
Last logged: 13:41:26

Migration handler not found for entry HeishaMon via panasonic_heat_pump/ topic for aquarea`

Recovering whole HA instance from backup, any clue how to workaround this issue?

**Comment by cjaliaga** [comment]
@formiification do you refer to the https://github.com/Egyras/HeishaMon integration?

**Comment by colseven** [comment]
same here:

Logger: homeassistant.config_entries
Source: config_entries.py:642
First occurred: 12. November 2023 um 22:09:48 (1 occurrences)
Last logged: 12. November 2023 um 22:09:48

Migration handler not found for entry HeishaMon via panasonic_heat_pump/ topic for aquarea

**Comment by cjaliaga** [comment]
@colseven are you using the aquarea integration? Could you show me the full callstack of the error?

![image](https://github.com/cjaliaga/home-assistant-aquarea/assets/1939768/6c0f415c-2cb8-4140-b8f4-04af9508ca06)

 HeishaMon is another integration and I'm a bit confused with these errors.

**Comment by thekeymeister** [comment]
I think it's the https://github.com/kamaradclimber/heishamon-homeassistant/ integration as I just had the same issue when updating that integration, this post showed up when I searched for it. 

For what it's worth, updating it to the latest beta solved my problem.

**Comment by cjaliaga** [comment]
Not related to Aquarea Smart Cloud integration. Issue on: https://github.com/kamaradclimber/heishamon-homeassistant/. Please open an issue on that repo if the problem continues.
