### ISSUE TITLE
Heating status doesn’t change to idle

### ISSUE THREAD

**Issue by otolizz** [cjaliaga/home-assistant-aquarea#60]
Hello,

First of all, thank for your work! It does nicelly what i was looking for!

I think i have an issue with the heater state, or maybe i am misunterstanding something ?

when the current temperature is equal to the temperature set, the heater stops heating and the status should be « idle »
But in my case, the status stay on « heating » as you can see on the image.
![IMG_4726](https://github.com/cjaliaga/home-assistant-aquarea/assets/53938996/213c6cbe-85b7-419e-9bb1-6b9a6740e277)

Is there a way for this status to change to « idle » when it’s actually not heating ?

Regards,
Pierre

**Comment by otolizz** [comment]
Hello,

Looking forward for this issue, i can see that it comes from the integration.

i think it does a set request instead of a get request.

when the integration is enabled on HA, i can see the heating picture on the account service:
![IMG_4727](https://github.com/cjaliaga/home-assistant-aquarea/assets/53938996/a7dd4a7e-7c6e-4143-812d-df662f5dc58e)

when the integration is disabled on HA, the picture disappear:
![IMG_4728](https://github.com/cjaliaga/home-assistant-aquarea/assets/53938996/ba4f219a-54c9-4612-99e8-393dcb586386)

So, i guess this issue come from a set request, setting the status of the heater on « heating » permanously, instead of a get request.

Can you check that point?

thanks a lot,
Pierre

**Comment by otolizz** [comment]
Forget about my issue…
It seems that it comes from my device…

i don’t know why but the integration on HA is still disabled and the heating picture shows up again on the aquaera smart cloud interface… !!

any idea how i can fix this ?
Do you guys are having the same issue ?

**Comment by villar3** [comment]
I have a same issue like you. but i think this is a panasonic issue side.

(in french: sur l'application panasonic le status est en "chauffe" même si  la PAC n'est pas en train de produire du chaud. )
