### ISSUE TITLE
Air condition units

### ISSUE THREAD

**Issue by vukisz** [cjaliaga/home-assistant-aquarea#63]
Hello. I have panasonic heat pump and separate AC units. Which are all accusable from comfort cloud.
This home-assistant-aquarea does not see my AC units (just paired them).
But https://github.com/sockless-coding/panasonic_cc/ see's them.
Are there any risks using both panasonic_cc and home-assistant-aquarea at the same time?

**Comment by agm15** [comment]
> Hello. I have panasonic heat pump and separate AC units. Which are all accusable from comfort cloud. This home-assistant-aquarea does not see my AC units (just paired them). But https://github.com/sockless-coding/panasonic_cc/ see's them. Are there any risks using both panasonic_cc and home-assistant-aquarea at the same time?

I have been using both for a while and so far no issues

**Comment by cjaliaga** [comment]
Thanks @agm15. I'll close this issue.
