### ISSUE TITLE
Fully implement water temperature zone sensor

### ISSUE THREAD

**Issue by egrigat** [cjaliaga/home-assistant-aquarea#9]
Having problems setting up the integration. My device is a heat pump "WH-MDC05J3E5" with 3rd party hot water tank, tank sensor, internet/cloud connector card. Log file attached:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/aquarea/__init__.py:54
Integration: Aquarea Smart Cloud (documentation, issues)
First occurred: 10:53:33 (1 occurrences)
Last logged: 10:53:33

Error setting up entry [my user] for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aquarea/__init__.py", line 54, in async_setup_entry
    devices = await client.get_devices(include_long_id=True)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 247, in get_devices
    ZoneSensor(zone_record["zoneSensor"]),
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'Water temperature' is not a valid ZoneSensor

**Comment by cjaliaga** [comment]
Hello @egrigat, thanks for reporting this, I'll get it fixed and deploy a new release. 

As a side question, does your installation allow you to set the zone temperature in the Aquarea web/app?

**Comment by egrigat** [comment]
Hello @cjaliaga, thank you for taking care of this.

All new, heating wasn't active yet... I can adjust the 'a' temperature in the app but not the zone temperature (no sensors installed and it's not the temperature from device or remote). The temperature I can see/adjust is based on the heating flow temperature.

**Comment by cjaliaga** [comment]
Thanks @egrigat. Let me work on adding the water sensor so you can add the integration. Let's see if after you have it installed, the climate entity works as expected or we need to add additional code to handle it properly.

**Comment by cjaliaga** [comment]
@egrigat a new version is released: https://github.com/cjaliaga/home-assistant-aquarea/releases/tag/v0.1.2 It should appear soon in HACS:

![image](https://user-images.githubusercontent.com/1939768/188903000-0f794dda-c57a-4903-9313-cfabe7463ab4.png)

**Comment by egrigat** [comment]
Solved, it's working. Thanks!

I can set the temperature for the tank but not for the heating flow temperature. But I can set the mode heating/cooling.

![image](https://user-images.githubusercontent.com/113016835/188906658-436a768d-9aaa-4cf6-8715-5c24f14cd311.png)

**Comment by cjaliaga** [comment]
I think that's because right now the integration only accepts setting temperature ranges if the sensor is internal but it seems if the sensor is water temperature, Aquarea devices support setting it.

@egrigat, could you please send me a screenshot of the Panasonic Aquarea page?

I'd need the main page and the page where you are able to set the temperature.

 You may need to disable temporarily the integration in order to access the page:

> Panasonic only allows one connection per account at the same time. This means that if you open the session from the Panasonic Confort Cloud app or the Panasonic Confort Cloud website, the session will be closed and you will be disconnected from Home Assistant. The integration will try to reconnect automatically, closing the session from the app or the website. If you want to use the app or the website, you will have to temporarily disable the integration.

Thanks!!

**Comment by egrigat** [comment]
Sure, please find below. FBH means underfloor heating. Heating is controlled as relative values adjusting the heat curve (for example +3°C, actual 0°C). For cooling mode I can set a fix value/temperature for heating flow (for example 20°C like in the screenshot).

![image](https://user-images.githubusercontent.com/113016835/188981762-1e3c9d58-9da0-4164-aff9-27454767e5c9.png)

![image](https://user-images.githubusercontent.com/113016835/188981880-44f522c5-5a88-4742-aa86-04dae3247e73.png)

![image](https://user-images.githubusercontent.com/113016835/188982967-b1454e0d-ad1a-48ed-a205-a73a7b05996c.png)

![image](https://user-images.githubusercontent.com/113016835/188981959-79a40709-2b8f-4850-9b7e-e9a027428349.png)

**Comment by cjaliaga** [comment]
Thanks a lot @egrigat for your screenshots, they are very useful. I've been investigating the scenario and I think it should be already supported with the release I just published: https://github.com/cjaliaga/home-assistant-aquarea/releases/tag/v0.1.3

Please let me know how it works for you.

Thanks!

**Comment by egrigat** [comment]
Thank you for your support.
For my setup no change since v0.1.2. I guess. Still only possible to change water tank mode and temperature. Change of device mode (heating, cooling, auto, off) also possible but I cannot change the temperature.

**Comment by cjaliaga** [comment]
@egrigat I think I've found why. I'll work on it tomorrow and release a new version. Will let you know when it's ready so you can test it.

Thanks!

**Comment by cjaliaga** [comment]
@egrigat I've released v0.1.4 https://github.com/cjaliaga/home-assistant-aquarea/releases/tag/v0.1.4 with the fix. Please let me know if now you're able to modify the set temperature or if there's anything missing.

**Comment by cjaliaga** [comment]
@egrigat I've published today another version, v0.1.5 that should have solved all issues found so far regarding setting temperatures. Please let me know when you have the chance to test the new version, that hopefully solved the issue 🤞

**Comment by egrigat** [comment]
Hi @cjaliaga , I can set the temperatures now in the correct way (+/- for heating relative to the curve and absolute heating flow temperature for cooling). Also available through homekit bridge! Great, thank you very much. Good Work. 

![image](https://user-images.githubusercontent.com/113016835/189497142-4c06ceac-6da0-41d2-b7c4-4f0376848cea.png)

**Comment by egrigat** [comment]
Update: I can set the heating mode through homekit bridge on my iphone (off, heating, cooling, automatic) but not the temperature.

In homeassistant both not adjustable, but actual status is correct.

**Comment by egrigat** [comment]
Maybe a Browser Problem. Will check on my own and come back to you later.

**Comment by egrigat** [comment]
Maybe a cache problem of the Edge Browser, it's working again after reloading the page. Sorry for the unnecessary traffic.
