### ISSUE TITLE
not working with new update ( heatpump not switch to active )[Bug]: 

### ISSUE THREAD

**Issue by Vivvo460** [cjaliaga/home-assistant-aquarea#95]
### The problem

sensors are ok , when i try to setup the heat pump( cold, hot, setting temperature) nothing happened.Same thing with tank.

### What version of Home Assistant Core are you running?

core-2024.1.5

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you running?

0.6

### Device description
Number of zone 1
Support cooling
Have a dhw
nothing happened when i try to switch modes on home assistant. It works all fine with prev versions 0,5.

### Is the integration loading?

Yes

### Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?

Yes

### Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?

Yes

**Comment by cjaliaga** [comment]
Could you give me more details about what do you mean with "not changing to active"? I've been testing the integration with my heatpump and it moves from heat to auto with no issue. I've been also testing setting the tank temperature and it worked and changed to heating the tank water. 

@Vivvo460 on "device description" you're missing the configuration of your heatpump as described in the form. Could you please fill them? Those details are incredible useful to troubleshoot the issue:

> Number of zones
> Does it support cooling?
> Does it have a DHW?
> Any other detail that might be relevant

Thanks!!

**Comment by Vivvo460** [comment]
The thing Is that if i moves from off to heat, It automatically turn to off

**Comment by cjaliaga** [comment]
Thanks both, this information is great. Let me check if device direct is not being used with the changes in the aioaquarea library. That could add some delay while trying to refresh the information.

**Comment by cjaliaga** [comment]
@duca2 @Vivvo460 release https://github.com/cjaliaga/home-assistant-aquarea/releases/tag/v0.6.1. Please reopen this issue if you still find any problem with that version.
