### ISSUE TITLE
Warning shown when starting HASS

### ISSUE THREAD

**Issue by afharo** [cjaliaga/home-assistant-aquarea#98]
> 2024-02-08 23:00:36.430 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.aquarea.climate.HeatPumpClimate'>) implements HVACMode(s): heat, off, cool, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/cjaliaga/home-assistant-aquarea/issues

I just noticed this warning when starting HASS in its latest version (2024.2.0)

**Comment by cjaliaga** [comment]
I'll take a look. Thanks!
